import { Box, Typography } from '@mui/material';
import { NextPage } from 'next';
import Head from 'next/head';

import { Hero } from '../../shared/elements/organisms/Hero/index';
import { AsesorForm } from '@/elements/molecules';
import { MainLayout } from '@/elements/organisms';

import HeroBackground from '/public/images/jpg/plans-background.jpg';

const Asesor: NextPage = () => {
  return (
    <>
      <Head>
        <title>North: Conviértete en asesor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero
          backgroundImage={HeroBackground.src}
          height="medium"
          align="center"
        >
          <Typography
            variant="h1"
            textAlign={{
              xs: 'center',
              lg: 'left',
            }}
            color="common.white"
            fontWeight={700}
          >
            Forma parte de nuestra familia!
          </Typography>
        </Hero>

        <MainLayout>
          <Box
            marginTop="6.125rem"
            marginX="auto"
            paddingY="3rem"
            maxWidth="40rem"
          >
            <Typography
              variant="h2"
              fontWeight={700}
              marginBottom="3rem"
              textAlign="center"
            >
              Conviertete en asesor!
            </Typography>
            <AsesorForm />
          </Box>
        </MainLayout>
      </main>
    </>
  );
};

export default Asesor;
