import React from 'react';

import { Box, Typography } from '@mui/material';
import { globalStyles } from '@styles/globalStyles';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { Button } from '@/elements/atoms';
import { Header, Hero, MainLayout } from '@/elements/organisms';

const Home: NextPage = () => {
  const router = useRouter();

  const { classes } = globalStyles();

  const handleRedirectToPlans = () => {
    router.replace('/plans');
  };

  return (
    <>
      <Head>
        <title>North</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Hero>
          <Typography
            variant="h1"
            textAlign={{
              xs: 'center',
              lg: 'left',
            }}
            color="common.white"
            fontWeight={700}
          >
            Encuentra los <br className={classes.styledBreak} />
            mejores lugares para <br className={classes.styledBreak} />
            estar en familia
          </Typography>
          <Box
            marginTop={7}
            display="flex"
            justifyContent={{ xs: 'center', lg: 'left' }}
            onClick={handleRedirectToPlans}
          >
            <Button buttonName="primary" width="contained">
              Ver planes
            </Button>
          </Box>
        </Hero>

        <MainLayout>
          {/* <Box
          component="form"
          sx={{
            paddingY: '2rem',
            display: 'flex',
            flexDirection: 'column',
            gap: '1.8rem',
          }}
          noValidate
          autoComplete="off"
        >
          <Input label="Nombre" size="medium" />
          <Input label="Apellido" size="medium" />
          <Button buttonName="secondary" />
        </Box> */}
        </MainLayout>
      </main>
    </>
  );
};

export default Home;
